# -*- coding: utf-8 -*-
"""grade-json-db

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zVxpSg9C7fnkmv58GqHw2STmZuzJkDet
"""



import json
# Open the JSON file
with open("students.json") as f:
  students = json.load(f) # Display the JSON content
print(students)

!pip install firebase-admin

import firebase_admin
from firebase_admin import credentials, db

cred = credentials.Certificate("firebase_key.json")

firebase_admin.initialize_app(cred, {"databaseURL": "https://grade8-json-db-6310c-default-rtdb.asia-southeast1.firebasedatabase.app/"})

print("Firebase connected successfully.")

import json

with open("students.json", "r") as file:
  data = json.load(file)

print("JSON file loaded")
ref = db.reference("students")
for student in data["students"]:
  ref.child(str(student["id"])).set(student)

print("Data uploaded successfully")

ref = db.reference("students")

while True:
    print("\n===== STUDENT DATABASE MENU =====")
    print("1. Display Students")
    print("2. Add Student")
    print("3. Update Student")
    print("4. Delete Student")
    print("5. Features")
    print("6. Exit")

    choice = input("Enter choice: ")

    # DISPLAY
    if choice == "1":
        students = ref.get()
        print("\nStudent List:")
        for key, student in students.items():
            print(f"ID: {student['id']}, Name: {student['name']}, Math: {student['grades']['Math']}, CS: {student['grades']['CS']}")

    # ADD
    elif choice == "2":
        sid = input("Enter ID: ")
        name = input("Enter name: ")
        math = int(input("Enter Math grade: "))
        cs = int(input("Enter CS grade: "))

        student = {
            "id": int(sid),
            "name": name,
            "grades": {
                "Math": math,
                "CS": cs
            }
        }

        ref.child(sid).set(student)
        print("Student added successfully!")

    # UPDATE
    elif choice == "3":
        sid = input("Enter ID of student to update: ")
        student_ref = ref.child(sid)

        student = student_ref.get()

        if student:
            name = input("Enter new name: ")
            math = int(input("Enter new Math grade: "))
            cs = int(input("Enter new CS grade: "))

            student_ref.update({
                "name": name,
                "grades": {
                    "Math": math,
                    "CS": cs
                }
            })

            print("Student updated successfully!")
        else:
            print("Student not found.")

    # DELETE
    elif choice == "4":
        sid = input("Enter ID to delete: ")

        if ref.child(sid).get():
            ref.child(sid).delete()
            print("Student deleted successfully!")
        else:
            print("Student not found.")

    # FEATURES
    elif choice == "5":
        print("\n===== STUDENT DATABASE FEATURES =====")
        print("Press 1: student list")
        print("Press 2: add new student")
        print("Press 3: update list")
        print("Press 4: delete student")
        print("Press 5: the feature list")
        print("Press 6: leave program")

    # EXIT
    elif choice == "6":
        print("Exiting program...")
        break

    else:
        print("Invalid choice. Try again.")

"""
Loop → keeps menu running

Conditionals (if-elif-else) → handles choices
CRUD operations:
Create → set()
Read → get()
Update → update()
Delete → delete()
Dictionary (JSON) → data structure
Firebase interaction
"""

